//
//  HomeModels.swift
//  BrazilTestiOS
//
//  Created by Mujeeb Ulla Shariff on 01/11/19.
//  Copyright (c) 2019 Mujeeb Ulla Shariff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
  // MARK: - Use cases
  
  enum HomeData {
    struct Request {
    }
    struct Response {
      var accountDetails: UserAccount
    }
    struct ViewModel {
      let name: String
      let accountNumber: String
      let balance: Double
    }
  }
  
  enum GetStatementList {
    struct Request {
    }
    struct Response {
      var success: Bool
      var statements: [StatementList]?
    }
    struct ViewModel {
      var success: Bool
      let statements: [StatementList]?
    }
  }
}
