//
//  HomeWorker.swift
//  BrazilTestiOS
//
//  Created by Mujeeb Ulla Shariff on 01/11/19.
//  Copyright (c) 2019 Mujeeb Ulla Shariff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
  func getStatements(completion: @escaping (Bool, Statement?, Error?) -> Void)
  {
      _ = Network.getRequest(url: NetworkRouter.Endpoints.statements.url, responseType: Statement.self) { (statementList, error) in
          if let statementList = statementList {
              completion(true, statementList, nil)
          } else {
              completion(false, nil, error)
          }
      }
  }
}
