//
//  HomeInteractor.swift
//  BrazilTestiOS
//
//  Created by Mujeeb Ulla Shariff on 01/11/19.
//  Copyright (c) 2019 Mujeeb Ulla Shariff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func getUserData(request: Home.HomeData.Request)
    func getStatementList(request: Home.GetStatementList.Request)
    func logout()
}

protocol HomeDataStore
{
//  var name: String { get set }
    var userDetails: UserAccount! { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    
  var presenter: HomePresentationLogic?
  var worker = HomeWorker()
  //var name: String = ""
  var userDetails: UserAccount!
    
  // MARK: Do something

    func getUserData(request: Home.HomeData.Request) {
        let response = Home.HomeData.Response(accountDetails: userDetails)
        presenter?.presentAccountDetails(response: response)
    }
    
    func getStatementList(request: Home.GetStatementList.Request) { 
        
        worker.getStatements{ (success, statements, error) in
            
            if success {
                let response = Home.GetStatementList.Response(success: success, statements: statements?.statementList)
                self.presenter?.presentStatementDetails(response: response)
            }
        }
    }
    
    func logout() {
        presenter?.logout()
    }
}
