//
//  LoginPresenter.swift
//  BrazilTestiOS
//
//  Created by Mujeeb Ulla Shariff on 01/11/19.
//  Copyright (c) 2019 Mujeeb Ulla Shariff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
  func presentFetchUserResult(response: Login.FetchModel.Response)
  func presentValidationResult(response: Login.ValidationModel.Response)
  func presentLoginResult(response: Login.LoginModel.Response)
}

class LoginPresenter: LoginPresentationLogic {
  weak var viewController: LoginDisplayLogic?
  
  // MARK: - Fetch Previous User
  func presentFetchUserResult(response: Login.FetchModel.Response) {
    let viewModel = Login.FetchModel.ViewModel(user: response.user)
    viewController?.displayFetchUserResult(viewModel: viewModel)
  }
  
  // MARK: - Validation
  func presentValidationResult(response: Login.ValidationModel.Response) {
    let viewModel = Login.ValidationModel.ViewModel(validUser: response.validUser, validPassword: response.validPassword)
    viewController?.ValidationResult(viewModel: viewModel)
  }
  
  // MARK: - Login - format login results & send to the viewController
  func presentLoginResult(response: Login.LoginModel.Response) {
    var viewModel = Login.LoginModel.ViewModel(success: response.success, loginResponse: response.loginResponse)
    viewModel.loginResponse.error.errorMessage += "! Please try again"
    viewController?.displayLoginResult(viewModel: viewModel)
  }
}
