//
//  LoginWorker.swift
//  BrazilTestiOS
//
//  Created by Mujeeb Ulla Shariff on 01/11/19.
//  Copyright (c) 2019 Mujeeb Ulla Shariff. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    func login(username: String, password: String, completion: @escaping (Bool, LoginResponse?, Error?) -> Void) {
        let body = LoginRequest(user: username, password: password)
        Network.postRequest(url: NetworkRouter.Endpoints.login.url, responseType: LoginResponse.self, body: body) { response, error in
            if let response = response {
                completion(true, response, nil)
            } else {
                completion(false, nil, error)
            }
        }
    }
}
